source:
  github:
    - token: blabla
      user: blabla
      url: bla.bla.com
      username: bla
      password: bla
      ssh: true # can be true or false
      sshkey: /path/to/key # if empty, it uses your home directories' .ssh/id_rsa
      exclude: # this excludes the repos foo and bar
        - foo
        - bar
      excludeorgs:
        - foo
        - bar
  gitea:
    - token: blabla
      user: blabla
      url: bla.bla.com
      username: bla
      password: bla
      ssh: true # can be true or false
      sshkey: /path/to/key # if empty, it uses your home directories' .ssh/id_rsa
      exclude: # this excludes the repos foo and bar
        - foo
        - bar
  gogs:
    - token: blabla
      user: blabla
      url: bla.bla.com
      username: bla
      password: bla
      ssh: true # can be true or false
      sshkey: /path/to/key # if empty, it uses your home directories' .ssh/id_rsa
      exclude: # this excludes the repos foo and bar
        - foo
        - bar
  gitlab:
    - token: blabla
      user: blabla
      url: bla.bla.com
      username: bla
      password: bla
      ssh: true # can be true or false
      sshkey: /path/to/key # if empty, it uses your home directories' .ssh/id_rsa
      exclude: # this excludes the repos foo and bar
        - foo
        - bar
  bitbucket:
    - user: blabla
      url: blabla
      username: blabla
      password: blabla
      ssh: true # can be true or false
      sshkey: /path/to/key # if empty, it uses your home directories' .ssh/id_rsa
      exclude: # this excludes the repos foo and bar
        - foo
        - bar
destination:
  gitea:
    - token: blabla
      url: bla.bla.com
  gogs:
    - token: blabla
      url: bla.bla.com
  gitlab:
    - token: blabla
      url: bla.bla.com
  local:
    - path: /some/path/gickup

cron: 0 22 * * *

log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7 # keep logs for 7 days