version: "3"
services:
  runner:
    # build: . # If you want to Build the Image locally (You need the complete Repo on your PC)
    image: buddyspencer/gickup:latest
    volumes:
      - ${PWD}/config.yml:/gickup/config.yml
    command: ["./gickup/app", "/gickup/config.yml"]